language: java
sudo: false
script: mvn clean install -B -V

before_install:
- sudo apt-get install expect -y
addons:
  apt:
    update: true

matrix:
  include:
  - jdk: openjdk8
    after_success: mvn jacoco:report -pl "com.github.dynodao:dynodao-api,com.github.dynodao:dynodao-processor"
      -B && bash <(curl -s https://codecov.io/bash)

before_deploy:
- openssl aes-256-cbc -K $encrypted_ba2684aa2cfa_key -iv $encrypted_ba2684aa2cfa_iv
  -in .etc/signingkey.asc.enc -out .etc/signingkey.asc -d
- gpg --fast-import .etc/signingkey.asc

deploy:
  provider: script
  script: mvn -s .etc/travis.settings.xml -DskipTests=true deploy -B -P release
  skip_cleanup: true
  on:
    branch: master
    repo: dynodao/dynodao

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
  - secure: "IMVEZX/cSKLxc59gaizUuSaUc4Vc/7QSC6Gy+yCYGraXrJiFYVOKMkjHbux0rCSI/wtnk0rLHRwqTswyQ9u/198+KESt/cG/vW3sQ6HEg+acRhAKZcW9cQS/xAYf7yd5uEhCiEVgjR0dU1hhWyEFumwsR0QXeUBdF5qg6oO/Ya8r2P7OEYpV73FdAitdYKMaVExshUJlOaoPikdWTPpugMaGEAmq4f8sBdjSBvetFp+nqayX8mGbMBUX/3TI0blk3xNXkgBpEIey2XZW+SpJWf13RJRonIu8E9EdVOeErC55UrnFVDe5kiIJv8+ErXdPXppCpLOwHuh+2NxkJ51GI8L91KqkMyxKBoOICvBeZ60aLSwNpJA82jmnsDdsS6c2ZYmTCanqVlXDuVyMv08b0bodNWR1WENF5zeWm9gEmAWeOnFlRlRlNiLh8TYA/GOwun8IPWVojQb/nlbqLSp4XPmwAL7Q6Y/kUwgoduPoxxPgAmecBDCYBm5fkh5tCBsJQejOEr+qpFZ0lYiLWhL+dYwnWnFX3rao6w4/h/KfIkavg6pgoudheFlMwuLVj0Lg2Li4ZgUwc0m7xYIrD78tJsmELR9jMCHpbdj9dvkVd+n6XABOv7XUHWTIOO3bvJH2l6nqdRqvlCuSeZdFmULgveJaxieOfj/yrfrIb8FZ03s="
  - secure: "G4gWafzskt9YZyuOTQZFxBWzZawkq0UB8dcEYNYvKpm5tVy1P++EIMz/lqG+1hp8zRNP/9GCKPoPhW1vgCms/9OnhUAJGbZgah4HG+rYrmfYw4a/dvvo3Ebb04ly57sgiPTrXuQa/a38gZTvinnvhdT7Q3xnHcnAm3CYWhci8VHSFkuDUpus7U8OoC0aT5bFeNk06WDGJudZpixg+nvjSF5GuHSUYs/t0QJOtHECZVxgK9YvQgJLdgncG62bRSvRy2Ui+dLsNeeFDrzNYbp/G5h7snj2+dyUxBceuYNrCnZF/snB66aiNgSaQIJEs6QUJgOYwFnfmPQLPsE34bcC0D8Y//eHdtI947oI/LPIAfcjzxt6vvQgWRrL6O3D9uzXruCvxkhiE/gg3rfjoTnpidLe6kFoQJ95ZBkRKUHxx84iyMQucyRbpqOdm5rjZaSNeev4MwooXegmn7Ch5ojJVVvQubqwnSI8598UwYQ6h5Ey5KPVjgd9U41bg6kknic7XOzD8l2MiJSIK0sYPtjW1zXRYEIv4vykTHgzQT7516a2pq/bWQ5xrqmBwBi/3jPxoDl5ni1R8b1XBfv3Tm2exlV1IQlJcO/wfMhaRCylJoWcPzK08jDDP+3G28nJuuyH8t2qi1WOI1HOOi7B9wxI6M5Zhs6f2iOkp0Qua5p6PUg="
  - secure: "CIZPZLF6NPMuHdZmbQP3eScww5aQtx16XnyS0I5RKp2t3x9C4TwUD4KstDl73RLTW51ctrWhsmBihF0GYBF1Tr6dj19HCtFaqUzquKHA3ayyAOZsdhlH3OrdgbvSkekz9V12w6jigpON2fzq6P0IzLxzGh4lmAJD1cKj/FiZJ7wrUh0JOMgiVxeGqPRXiQwbRHFn/5s7sVYBEP7i8+4FFUGd4fHy50oNCgcswrVMwLyjsl4WJpQEdx+W6+PYT44cOIvYJdSyJDZ0dP6dW0t8thzD+o2GBeUkfjW8LCg1ZkHREFwf9WyVSpT8E+KzE+xknBTpKl3tZyuEm1yoh7BhV0FaObfrSrglXtbcCe6HgIOoQVtIVRNVsvnWp6VzqGbw5xSwdjCrP9oki7mAMouhCd672OtmW1JrGoTghLZR4W1Ym3FOJRYAIEaTxS5pWAhj0Dk0O+4jfSWfgpmQYL5Ywnnb24GZK+Gr2Alx5HVFJglI56P5xClhxLinpwZ6G0jd7U9ldJMgScLlbPaPdSOgWWGw54Bo51dLQJQhiL5HTmZx+CzLh8QuxzsnIjpun7vlzPejKKDSD5BKFFvhihNabd7WBQaUVjfZEkpTEK+ZSV4ZWbO7NtwwZSMdJHFvQwvu0OR5EH1Oxbmz+d/twB2QVe6ywBv+OQmt+jHy20shXBI="
  - secure: "z3HyLIY81X9YI22RtE659pSbcBwLyifOrt4PwAI7Bk/AYAXcRNMGVrELGzgoc/0JMbbrLTlrM9w93WazIeV/7l6M3/yIVahD6sDtFe/RIUb+/S4yCxJIyZtNF19ppwDhsE+8opT0xYvMo+WLhdB/3iqEuGS58BsFaeINXeWK56JfE2diqazW1b+1ktfc7AB8h4udOP6rInXrtlUx0z3KeXSCKBkfnA/h1yNC+NHTDhIAMfCctg1dR4BHR0Tktlg5XyZ3/xxx5NDsIW1TOa3Rqyrcm9JBKoR4izg/SwNC07QllXxEpoXAFiOcyidM7ddRbgiNhDu6IkEcM0WCv1wzFaaJ/jeT5VROLC0CIwqE0D4kESEFCLPSZJMBdPW1b15BEB5ocB+BDgxJOmE+etORho/VkXY1oaV4AgyDPxKhV18ccmkQPH5JKo3nYYUTZwksSxFkdkwl6HhEV4vwz9gE9kKBOyQTjGalBSprtjgO0NyfUIKEx4c2zCoNYhQ8G4S0+VE6iO0dDlCchaQcX6l4Led2EH5v/FjWevCfBiW21O5jcXR47X6Wa0BxTXlLNXsMAUSgJiwipiZQbk+BGp6kaiSNFRKF2zZ8HxpjTNajclVxDWlyvnVPNL+6uOn7+5tzZa63SpmxlTHP1p8c2zrCly2FiokJ7IGbzauQTlQHohI="
  - secure: "mEW50oPCv0fXDBIxKU9bCPvhyaz8oiadSquRtJrFlxbMhLUPJNyXoj0vnDOi8fgCCEzqt94sQNRkYaMd48UQs7XLyltKEZUapR5WDRkVycyPahgw1Dex5wwGaFlC9nbUcqypPGPE9JaR9JKlrxDkGqqVcvK1m7zpb1SgFtk7kYEpGpl1NJ3J3KJKuDGAYv5CHT0mMcivo7xWZxqlkmBf5tLEzcPKKoxUyHLMsnY8vAY+vDtC2IPm/9P40Oo85XNPswHAOAwpzcNqHU1rc79ggm2YxJXAZw5BViHd9BviZcEz4uIHcWKFGS9EB8snyBeiC0iirw1PzeqQfMjpsX1Cop8dximQHtcPAwb1FvjCMgACkQ2PTiRXGxpWidaeVbeGYTr/MZ4BWAz9cesEmLHCLQEI3WMzmIw4lNF38W23UPmUXdAezIHQxrA+BSiZPP+W7vCTq8CDjgGlBYAxvRtagJewI5RQz8TSSU4YS3Z49rEuarrvaDYCaLJWhWNZRgzNEM6lUaL3AmCu8CN+2Af1qDjjPPv+gl89lq3pm/tVVQYx74d0j5DZZUp2OZQ+PhcPORl2iLleE/baEpUgai2OoM3Q8zVu/neZaGHd0Op+BuZKsk4hXXommZ2rtbGAgX2SVzW/g/J+TQpaZs8oCjWG53zid/Lk/OkqxyecFZH27jY="
