language: java
sudo: false
script: mvn clean install -B -V

matrix:
  include:
  - jdk: openjdk8
    after_success: mvn jacoco:report -pl "com.github.dynodao:dynodao-api,com.github.dynodao:dynodao-processor"
      -B && bash <(curl -s https://codecov.io/bash)

before_deploy:
- openssl aes-256-cbc -K $encrypted_ba2684aa2cfa_key -iv $encrypted_ba2684aa2cfa_iv
  -in .etc/signingkey.asc.enc -out .etc/signingkey.asc -d
- gpg2 --keyring=$TRAVIS_BUILD_DIR/keyring.gpg --no-default-keyring --import .etc/signingkey.asc
- expect -c "spawn gpg2 --edit-key A9C96D5B27E6390733A4DEF73ED8EF3F9F7CE8F2 trust quit; send \"5\ry\r\"; expect eof"

deploy:
  provider: script
  script: mvn -s .etc/travis.settings.xml -DskipTests=true -Dgpg.executable=gpg2 -Dgpg.keyname=A9C96D5B27E6390733A4DEF73ED8EF3F9F7CE8F2
    -Dgpg.passphrase=$PASSPHRASE -Dgpg.publicKeyring=$TRAVIS_BUILD_DIR/keyring.gpg
    -Dgpg.secretKeyring=$TRAVIS_BUILD_DIR/keyring.gpg deploy -B -P release
  skip_cleanup: true
  on:
    branch: master
    repo: dynodao/dynodao

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
  - secure: "YUimMO9ypZ8AtBlIcDGA4a3A54hy7mUkLdPYReMCb8MMye8NK5cX26Rkq0ROS87TYf5boJclXT99BeDrizwArXIjO2YwhEJoZ2teKWN4T3kuvXisKDZELt+jYpATXyy2+sPHlPM3nECCWLRJYPjwJ8TqP1ypO4n95MDaHCB7Gqcip5f+GusweQxKftYc0GRdKuFKKtCmhHYN4cSWOCbw2ygDqlKVXS5APncEwxiYJhQvqgO80PKzDfB6Y+OfrZG+5mgokgWxnRvfdE8awcRJWteUVzRSWBU/WYd3SzPG+L9a622IB9J4Ms6d8T1vDwGfhDbUqXFdNE2i7tAVgiTDNXt9Xf+jsFe4ezMinIm0zviqYE4aPCXqH5JGyEUI9yaVn+f4Qgh7QjPiW014sJtpi41I/YSEqf+fBdOVla4+F5XnRmbiiTIKwpML5HqmucnLvf9nLtNvdVE5nKnIdzEhWAigLbdh8dTkYgWEMg/zubNplvH59MYtLQ3XGcZQgCPdbaxEQ97Jtt0W8gOyUUNBZ+NF9b0hrhhvCN0n3GPZTmHUCqhofUG6L5w8MRvDY/6gGj5SdsNR2d4mW+7tg9WdhFkiHV0cbJZNnMo9wjvp1SahpyF8hpwjQ7ioTT/ahF8wh0q3+o7lRgg7sQors9Ty4zhrYbOcVBKio4RoR92o/kQ="
  - secure: "dHk6Z1PT0xMLAd+Ll7hNz7UbKxC7Er/M4IN7GlKSQyKsOJZQkyj0fgaM5MuZfeZyJW6tKUiuOX8qJa5KT3bmTYO0pLzkImpqmmVDEksTLOs0WiX3kFO+bswoBuX5Eb67yKITV0Gnhg2+L1iyVOVjj20hAW8Bf4TRrLXQcIXK1QPLeGaGj2eFfD2eBDB6ehawd/DYfQS3L6mO5ViXSgxEbyou0Tnjkc9da/z7v/X74SparG2sw32TLgLIRFvcXFOsenQWWE0yhFAod9No0O7dYlTEBZ520QJ1HfzMQWtYbvZAStRhTnf48MjgQz1jjnGldd2uYZiRGjUKuDpJdbcsNtot8Hf+ir7pBP6XaO2Kd9rZumj/PrDuCy8eJG9Le4PvwNQMwixFLsUQ18NZJIF5uNqLms6sdZWWLvkUr5Siev14TIL7rBajNJOc+gCubMZLE2rCguDEZv/u54ylR+3s3lin2dTusClMT2TzXheaEE/2M7HohhDwpnZeAArFKcBf6BbsTrEfsjv/yWTMx9IJc5HRFI2vCcX79tDJrwmifFHH9KRtV+OEfBINoxzclnl3J3SkHn1YwsxOzyNOtTLmJG9WJvuNEnn/1raMboUR6S9zIsxNGQsvI58Bi0giFsz1fFEAPJmTEc4ce7Al/IW0m5QiPEAIKCK05j5OfVNscy8="
  - secure: "ThnIGWbFS9BoCvBMZl1ETzYXoWL/Pm6VbcvXwzZTWRxczM/o+QdZ3SlgXwK+Za3nnWV3OUi/Q0+/A+oQRPdZ7AfFDC2GI5M1BVW5EHHgh2Vba25+7XDFJ6oU8a76avDGJi+XwxmvJW4C6P1qm4cxHkpy8W7wxg8aVUXuZ+VifHlNX3DhM6HNjpCV151Ro132QjlMcpB55z3Yy22+GBr02GWgd53MJwfMNR20Ccx4rCzvSvXuwRH+g+KZvhSWyzhDYEVVQrLlPvI7e/1ZhOnQNiuNqwpuPdVs51B8LYDEoffxVfXXHjHc4cvo2jHe48QIumKsCbxBH7jlUJZoCXsbBzQEoYBf+IMBnxfi4w00ZUpRTc5xSIYYSTbM4vOiCN+OQQgQoV5TSapdxhZ7koGgDgbfyaqwcL1V9YVRui94XKQ78y9RckL7+5cp8S3zbcVdTRgSYsD1YGVOq1GgPjChCX+MvA10Gud8cLiJmdxV4xT7s2K8aPzen/oHz4lfPWsg1TjeK40g0ff/+STFSyBqyAQoQ0a31RaCvh3Thq4DD64xoRuX5CoI60y5d4Q6N+m0H9YYIc66Aec+ioXrQd/m1ZyZKkWS348bLOb+tMkE0ZyNIzseplhQMtN96BMLTZNNFEUm1AvWW99BOy7igFtGTGw7GN4ItbVkxmrYttOyHW0="
