language: java
sudo: false
script: mvn clean install -B -V

matrix:
  include:
  - jdk: openjdk8
    after_success: mvn jacoco:report -pl "com.github.dynodao:dynodao-api,com.github.dynodao:dynodao-processor"
      -B && bash <(curl -s https://codecov.io/bash)

before_deploy:
- openssl aes-256-cbc -K $encrypted_ba2684aa2cfa_key -iv $encrypted_ba2684aa2cfa_iv
  -in .etc/signingkey.asc.enc -out .etc/signingkey.asc -d
- gpg2 --keyring=$TRAVIS_BUILD_DIR/pubring.gpg --no-default-keyring --import .etc/signingkey.asc
- gpg2 --allow-secret-key-import --keyring=$TRAVIS_BUILD_DIR/secring.gpg --no-default-keyring
  --import .etc/signingkey.asc

deploy:
  provider: script
  script: mvn -s .etc/travis.settings.xml -DskipTests=true -Dgpg.executable=gpg2 -Dgpg.keyname=A9C96D5B27E6390733A4DEF73ED8EF3F9F7CE8F2
    -Dgpg.passphrase=$PASSPHRASE -Dgpg.publicKeyring=$TRAVIS_BUILD_DIR/pubring.gpg
    -Dgpg.secretKeyring=$TRAVIS_BUILD_DIR/secring.gpg deploy -B -P release
  skip_cleanup: true
  on:
    branch: master
    repo: dynodao/dynodao

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
  - secure: "kPVpbwOv7ncE/6oekuL7lNfTu3z8de0O1pB9RfxQv4XcsoiaOvxdeZEv1KaR8EayCIgfODG0VlWh2PQWJmFTLYo2Y7zfvb8hyAwZAHqIQDrmPhopmGGQImtoeEZYNUqZCMWDMIWCVwjTyxemreHypyIH3vEEgVriGAehBT6cFH/v8WfbaxKfQqMFWExvAsag9tlEwJOVMkO55nSxg9qq9pvXigs4I8LKky6pjiDM7xE3zxZpxztvGMXy+v6ow7bTc5Uqmj+Jwljz9iGayqy3T2vzuFcxHndVOMrl83nMhKR+1hW1ejNVYIT0cA0q1dHpNbrpMnS4DkAthZnM6gXgzalHV11Qe+/3RNRd/9wfKc4XmU9eC7MNfR/2bimN/4bTmPnX+UAB4YHvoVVjCQ3WhRqjLXfNwjgPD8Xa4dTwwqQJ2g9aG5TYVEyyFbtYyKWuPy3zB4G6EQAlFRF+8cAxmYH1gqrlqn1ULAO04ZvyPZhq6RvafJS8coBWXXw33+TlCPWRmZpT+Mn4KjfkGVCGaH3JP0+zTmBKv6rQ7ekUW5nqVVEzZei34Sfx4AQTYOpykz6IL/17JACIh+uNtCjrh6JzsJ1u2M2eKgi7QXMYwi9kaDL101ZnoqT4qP9yDaziv4tIFaBI87JQKKJV+gZQm1pCp12/zupr7kL/SnHjG/I="
  - secure: "r3J7CXTScROuCiDeQMOzLGJaUlels4TFjLEHMSMIUqt565prDD40HTSzL+koTcKmAAvMqOlMneCLWWxqaOIsMp720Ib6twykFME3OLKcwTmTH/ULjVmjI9OlhJr7aPaOvyja2qrZBhLQ3AQKb1Agpa/0v1R7K3ZgYEzHhniVLMNcEC0ynyYaPhA74uqABOXBTVudfP1g7T83cilN2W+RF//TauchLZg2A+iv/FYM4NOZoQ+gS8Y2n0qgG35ECAx+h5uQU/tzgUwJH/iwW6aM+SKD97EmWn5a0Cy0BVCFw62QDaXdBg0Q8SRDvw4nY8FPhTv4ua0ZSNbomDeEt2gOzgFKbHu+Pn1SQGhWRg3Dk8dINPObdN1Pko4tpPxqUdKTQm1mAj58Skx4zfl6Bb0NJ3YBJ1zIs61uXD81Vbu5TeWa0usUNi2rPnsbBMD+18fNOLxlynQW8HkTes/grPnUoUoCeHLif6gMrGWdUeygc0HfHYWtoJwSIyNjkfnLMs2G5u3TaXnOJflWp3IHZXUnX/0nDgzWKlhsdrjSX9N5yflqskfScAMuAvU9+n4V/1VO7621FTX0tcgZZOt+gkbFk7ZHhJslWS5SSKYgbn3JJC0HoMD/vnjnISQVmbgjocDZOWZesfhkOcJlDTmUfbqfGM9CG7/IQBQFZGXMNOPnPV4="
  - secure: "OC90XZ07GcOrgZ68bsV3FS+aWTF1/cm1EwOkT7AXg2qbc8IMPrCzWLQIN7I0CdgV5HG4gro4R6R2kLV9lO2hEahW7THjLeDV/Q4o0t5d24HDvzyLPkaZySZda2XUWYP2a5j7CFq9aZT17gCZXaoKmNBbcY9tOC7BO+GJ8UF+c2+5YkaUGG+8HsJhNhnWA69UUKclmRRszoigk802kUUSin69SCqt7/iW7LtLaKXxSISGREF3fvfHhKoScIYOMmi5zUgvhZVf/K9SCdWQ3EBoqz9IAbQnRMA0WnOapKNV918cd9pdR0QDimLd+x4eitHNC/wlSRwg3v/HnYHkQ1XbOs+idVn9qCkDCz5uBgcFHsV+yc3QMK936EP4GEBYHv35spQW/6vJFr7G7hPMQaaXHsXDozRhQd0+nvUvxn7NJqk+XkbQ6MdGjFaIWyj+bai3yUlpGD72pQfwIAm97x8oJlM4stJlMAM+fR+CkTE5Mo/UuKmDNBr/I0raSKrAL8fT5oeyL9AAe3CT+TshzE/pzxncd2Fw4I9HHMTlAdmaig2RG2C+WW/pHONftzuDv4fGU4ou/WeZAvsbChxmTCpSymMGAR8KRF1btLBDbyn37gQ9jPoSomkOwK+4cjbHklLFUp339K9flqFuNYybimYphRDAGg+jBSLpVm2mMrlXlVI="
