language: java
sudo: false
script: mvn clean install -B -V

matrix:
  include:
  - jdk: openjdk8
    after_success: mvn jacoco:report -pl "com.github.dynodao:dynodao-api,com.github.dynodao:dynodao-processor"
      -B && bash <(curl -s https://codecov.io/bash)

before_deploy:
- gpg2 --keyring=$TRAVIS_BUILD_DIR/pubring.gpg --no-default-keyring --import .etc/signingkey.asc
- gpg2 --allow-secret-key-import --keyring=$TRAVIS_BUILD_DIR/secring.gpg --no-default-keyring
  --import .etc/signingkey.asc

deploy:
  provider: script
  script: mvn -s .etc/travis.settings.xml -DskipTests=true -Dgpg.executable=gpg2 -Dgpg.keyname=A9C96D5B27E6390733A4DEF73ED8EF3F9F7CE8F2
    -Dgpg.passphrase=$PASSPHRASE -Dgpg.publicKeyring=$TRAVIS_BUILD_DIR/pubring.gpg
    -Dgpg.secretKeyring=$TRAVIS_BUILD_DIR/secring.gpg deploy -B
  skip_cleanup: true
  on:
    branch: master

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
  - secure: ONP2Yu85ctGwvYfYG31YHxlIQcaf0hjd31XdT0El+xekV12X+0GhwzyyNibJAkvPBMhVEnN3Bin3U8hQe5UOaU4+CsjfEtnfb1U6YJfPt1MJ9MvRLSmm1miPBtFtTr1qt2p7el10sopTGKYsLe53axFZFpD4PWeZpoRX26SOXwRJw55coMQOdNMxeckC+GF3bLUlrMD4i+IBIg8mT7jSn6oj6i/tqg6Fn9gxo+HvYGQ6lTckk1JS0mj1Xb2A8+O1dEIgnm2orYmLwCWVjtId3MKdCjQR3nef1Ok0Uut2RUb8RsYRP067oEPCR7z7Xe4vaYtcr6DyHYkbyTMNu8htCG1QJtWOCnFm2ySmKbOvNQuN8chhhu0dcIpA1hTLsWhwDc91X4fprljAS0b6L5RHFUbuBQy2uvGOC9e6xkmpQtI+xnrNdTbpcdK0sVCSYlegzenCofTmaOdaUMdUeTTINVK1oYzerI0IocdglCKX0KBE+2VCg1bbZupCe//zAivd45WUuO3uVJiEiU9ttTNsWYiX/wLsexWBQy9AT7b3Oywy0fjyQlYStIToFjl6OUCLskGkjdvlXXQrXWsD3YOTkOpoCiEQ7sitwVE8xYwNwU60q2AHU6RNOyE+vEr/LT0tmiOCJckHEZjzWVObpUa9G+x9JYZkYSGog0hZjcBmGEw=
  - secure: xY4xvnBA2vXHnRF8cmKG5TcEjZzClGuI95s6yhBQA/Lo0iDjYZBFM8X7gEpiQx7SSu4E+HWkqHxmPdL4WWPp63ov6OPM2hJoo4id6+/XNeZQ29ddCsbgLywW+99aE4ZH7ogEWWMPiJP8lfNfjka9pozW1zM8jYkzwwCsESqWUKgFPtucS/Cb+39+gzDukdGQghFqrUy9DnJHJnKC07Kgn7yGJIXOZsY5qetv6zNQ7fPIMuCWdCHFqYbrTRO1rpHO2GJtY2uhZsKyB6fMULWj24SN+LEKGh+RU19HG66Nx1iyt/hvtbMtmcIy02lavWK3WXLd1K0Zz8Hkegd8hZ5duKCOLg3cTqjKoKTVUwQ9Ri5ERt9buzDB4Cu2qBzMxJw+fvMD5lTln3ULzkwTtc43ZZFeaN9MLcPmpDDbv5Uy91oxcrEmdwWdHS26cKrjow3DfpiixZEPKe3RtGhszxJ63XyfrTuEL+Z9rdf/g0FJ36jCGPKtoeEcumyq5UZta/qyGJn3jMtx6hNIOE/HQ37qfQlgt3keF8IwIDvHwW+8hrvOXzdU+A1/tVAXnZqsxu7dNamfcWq2MACQ0EHq7kiyh+IkBVv98piSJPx0LYe/LWX7iMEIs+u4aFzbrr/kAyvtJacGus8Ew3T4sbVCYcXuhn2Eb1V2bUi9KUBMUwt+6ts=
  - secure: GaOmqalTs5Xa8axrRdff8PZt/B8nlQiSfDDVsIDKzJ/i2QL3CcRoTbVF7HNI+Xb4zDMp/MHyTMBVJWvuDHfUGOhm9mppQN2hvg7/Per3yw6+CW/fVfb2SgNszeYKJ86z53HboFmSTPf2k8aISyz/Cjy8wqehTCccgYflzuJWTyXyZpPFXze5NzDNSyMCS4x8QjBZNQiouXcL4wtdAbvTYhdP+ZBdfgO2VflIETCn0WM4F3n0IenFKxHH1SraewN+pb298g5pU3H0MWXGdMbYUYfo/nNuYpXMLWuj3v+fLeUG7blT52HHbfDcbI1y1TXNhKXWwWi3gHVudb0nfuOQabgq3G9EKqcT19TUj9gbJeQg2dXxQ0v8MgMhpVP+DhzH/bR70B/5BR2N8qnrgeHMdUfqxgO/DthPCjPm2UpIJLHlCZHD4y4i9rx97obpHtJMTUW+ncsYbPOfxZ6Jcl89YEJQL4j11NVGGeBUpupM/Vg/2+fntbu4whlKuEOE448Q+5AdU60qSLzKvwflYeJqY0By4jVNRDet2eQsR2NzLamUjCX3EoCtNPcYVg5XHbsmqTGPd33qiN8izxXXPvc6dwLJg+vdgObyJDFrf3l1A9QtPFc7v563doI+jdFvIXo7aP0+W9hdT+pDoGeYMYEmJBq2BuS5rMt5VywG0IONTGc=

before_install:
- openssl aes-256-cbc -K $encrypted_ba2684aa2cfa_key -iv $encrypted_ba2684aa2cfa_iv
  -in .etc/signingkey.asc.enc -out .etc/signingkey.asc -d
