language: java
sudo: false
script: mvn clean install -B -V

before_install:
- sudo apt-get install expect -y
addons:
  apt:
    update: true

matrix:
  include:
  - jdk: openjdk8
    after_success: mvn jacoco:report -pl "com.github.dynodao:dynodao-api,com.github.dynodao:dynodao-processor"
      -B && bash <(curl -s https://codecov.io/bash)

before_deploy:
- openssl aes-256-cbc -K $encrypted_ba2684aa2cfa_key -iv $encrypted_ba2684aa2cfa_iv
  -in .etc/signingkey.asc.enc -out .etc/signingkey.asc -d
- gpg2 --keyring=$TRAVIS_BUILD_DIR/keyring.gpg --no-default-keyring --import .etc/signingkey.asc
- expect -c "spawn gpg2 --edit-key $EMAIL trust quit; send \"5\ry\r\"; expect eof"

deploy:
  provider: script
  script: mvn -s .etc/travis.settings.xml -DskipTests=true -Dgpg.executable=gpg2 -Dgpg.keyname=$KEYNAME
    -Dgpg.passphrase=$PASSPHRASE -Dgpg.publicKeyring=$TRAVIS_BUILD_DIR/keyring.gpg
    -Dgpg.secretKeyring=$TRAVIS_BUILD_DIR/keyring.gpg deploy -B -P release
  skip_cleanup: true
  on:
    branch: master
    repo: dynodao/dynodao

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
  - secure: "IMVEZX/cSKLxc59gaizUuSaUc4Vc/7QSC6Gy+yCYGraXrJiFYVOKMkjHbux0rCSI/wtnk0rLHRwqTswyQ9u/198+KESt/cG/vW3sQ6HEg+acRhAKZcW9cQS/xAYf7yd5uEhCiEVgjR0dU1hhWyEFumwsR0QXeUBdF5qg6oO/Ya8r2P7OEYpV73FdAitdYKMaVExshUJlOaoPikdWTPpugMaGEAmq4f8sBdjSBvetFp+nqayX8mGbMBUX/3TI0blk3xNXkgBpEIey2XZW+SpJWf13RJRonIu8E9EdVOeErC55UrnFVDe5kiIJv8+ErXdPXppCpLOwHuh+2NxkJ51GI8L91KqkMyxKBoOICvBeZ60aLSwNpJA82jmnsDdsS6c2ZYmTCanqVlXDuVyMv08b0bodNWR1WENF5zeWm9gEmAWeOnFlRlRlNiLh8TYA/GOwun8IPWVojQb/nlbqLSp4XPmwAL7Q6Y/kUwgoduPoxxPgAmecBDCYBm5fkh5tCBsJQejOEr+qpFZ0lYiLWhL+dYwnWnFX3rao6w4/h/KfIkavg6pgoudheFlMwuLVj0Lg2Li4ZgUwc0m7xYIrD78tJsmELR9jMCHpbdj9dvkVd+n6XABOv7XUHWTIOO3bvJH2l6nqdRqvlCuSeZdFmULgveJaxieOfj/yrfrIb8FZ03s="
  - secure: "G4gWafzskt9YZyuOTQZFxBWzZawkq0UB8dcEYNYvKpm5tVy1P++EIMz/lqG+1hp8zRNP/9GCKPoPhW1vgCms/9OnhUAJGbZgah4HG+rYrmfYw4a/dvvo3Ebb04ly57sgiPTrXuQa/a38gZTvinnvhdT7Q3xnHcnAm3CYWhci8VHSFkuDUpus7U8OoC0aT5bFeNk06WDGJudZpixg+nvjSF5GuHSUYs/t0QJOtHECZVxgK9YvQgJLdgncG62bRSvRy2Ui+dLsNeeFDrzNYbp/G5h7snj2+dyUxBceuYNrCnZF/snB66aiNgSaQIJEs6QUJgOYwFnfmPQLPsE34bcC0D8Y//eHdtI947oI/LPIAfcjzxt6vvQgWRrL6O3D9uzXruCvxkhiE/gg3rfjoTnpidLe6kFoQJ95ZBkRKUHxx84iyMQucyRbpqOdm5rjZaSNeev4MwooXegmn7Ch5ojJVVvQubqwnSI8598UwYQ6h5Ey5KPVjgd9U41bg6kknic7XOzD8l2MiJSIK0sYPtjW1zXRYEIv4vykTHgzQT7516a2pq/bWQ5xrqmBwBi/3jPxoDl5ni1R8b1XBfv3Tm2exlV1IQlJcO/wfMhaRCylJoWcPzK08jDDP+3G28nJuuyH8t2qi1WOI1HOOi7B9wxI6M5Zhs6f2iOkp0Qua5p6PUg="
  - secure: "CIZPZLF6NPMuHdZmbQP3eScww5aQtx16XnyS0I5RKp2t3x9C4TwUD4KstDl73RLTW51ctrWhsmBihF0GYBF1Tr6dj19HCtFaqUzquKHA3ayyAOZsdhlH3OrdgbvSkekz9V12w6jigpON2fzq6P0IzLxzGh4lmAJD1cKj/FiZJ7wrUh0JOMgiVxeGqPRXiQwbRHFn/5s7sVYBEP7i8+4FFUGd4fHy50oNCgcswrVMwLyjsl4WJpQEdx+W6+PYT44cOIvYJdSyJDZ0dP6dW0t8thzD+o2GBeUkfjW8LCg1ZkHREFwf9WyVSpT8E+KzE+xknBTpKl3tZyuEm1yoh7BhV0FaObfrSrglXtbcCe6HgIOoQVtIVRNVsvnWp6VzqGbw5xSwdjCrP9oki7mAMouhCd672OtmW1JrGoTghLZR4W1Ym3FOJRYAIEaTxS5pWAhj0Dk0O+4jfSWfgpmQYL5Ywnnb24GZK+Gr2Alx5HVFJglI56P5xClhxLinpwZ6G0jd7U9ldJMgScLlbPaPdSOgWWGw54Bo51dLQJQhiL5HTmZx+CzLh8QuxzsnIjpun7vlzPejKKDSD5BKFFvhihNabd7WBQaUVjfZEkpTEK+ZSV4ZWbO7NtwwZSMdJHFvQwvu0OR5EH1Oxbmz+d/twB2QVe6ywBv+OQmt+jHy20shXBI="
