language: java
sudo: false
script: mvn clean install -B -V

matrix:
  include:
  - jdk: openjdk8
    after_success: mvn jacoco:report -pl "org.dynodao:dynodao-api,org.dynodao:dynodao-processor" -B && bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: "mvn -s .travis.settings.xml -DskipTests=true deploy -B"
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8

cache:
  directories:
  - $HOME/.m2
