language: java
sudo: false
script: cd dynodao-parent && mvn clean install -B -V

matrix:
  include:
    - jdk: openjdk8
      after_success: mvn jacoco:report -pl "org.dynodao:dynodapi-api,org.dynodao:dynodao-processor" -B && bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2
