language: java
sudo: false
script: mvn clean install -B -V

matrix:
  include:
  - jdk: openjdk8
    after_success: mvn jacoco:report -pl "com.github.dynodao:dynodao-api,com.github.dynodao:dynodao-processor"
      -B && bash <(curl -s https://codecov.io/bash)

before_deploy:
- openssl aes-256-cbc -K $encrypted_ba2684aa2cfa_key -iv $encrypted_ba2684aa2cfa_iv
  -in .etc/signingkey.asc.enc -out .etc/signingkey.asc -d
- gpg2 --keyring=$TRAVIS_BUILD_DIR/pubring.gpg --no-default-keyring --import .etc/signingkey.asc
- gpg2 --allow-secret-key-import --keyring=$TRAVIS_BUILD_DIR/secring.gpg --no-default-keyring
  --import .etc/signingkey.asc

deploy:
  provider: script
  script: mvn -s .etc/travis.settings.xml -DskipTests=true -Dgpg.executable=gpg2 -Dgpg.keyname=A9C96D5B27E6390733A4DEF73ED8EF3F9F7CE8F2
    -Dgpg.passphrase=$PASSPHRASE -Dgpg.publicKeyring=$TRAVIS_BUILD_DIR/pubring.gpg
    -Dgpg.secretKeyring=$TRAVIS_BUILD_DIR/secring.gpg deploy -B -P release
  skip_cleanup: true
  on:
    branch: master
    repo: dynodao/dynodao

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
  - secure: "miBVn2iT5Wzx+M+Y9R13w4/312N8bADem44X/1lbPgupsoc7sGkyinIK/Ob6EP6ZDanBMCe7VotmHxPTSBFR8ftc1JhoNg/zndgLfW7SIfxhFmsAGFvdAe1ixQfhn55d8iw5LlE5tKgU2JVtT4qCr9m6n07z6/j46Bv4mUNqnMFtTaHYGf/VKhDRk+c3wYU9wAleHqGVvrcB1VuDHRWl+GkbXw0UAEok6Ny+R207KwrdLRwQD88c9/fxkLxcEhV7FTwrV/SL/VLWRoBkPlBzQR44gucAnrBtl0zJVer+yj36UNjDFTfIxL3th1ohPCrw3y3b1GFSYZeTHnHC7Oy2wpv/rdsJROwf6hBVXOCOILOcEiX/jIfVN6p/e9N2D+Dhqh9H3cP0cLsGDAczQLaqsIPOcYTOtAy9ODwbsi+jJWN3C8RNxyPix+OfpefvYseQEgn6IF/0lm7h/8/a+PzeID6vGMtUbAKRkYksnCkq95iFW2SMGZv/hiAgANeIMlMd9atOuYwE061SwkX924+p5OXDuHM6krGO+Hp3o6agkaSyW2Mrgp8cDxTIRfcyqpAuY+QSsssJEME7F+6bemTD699DqPIyAiaHJ/ft75veuBUVs/+6HnYgm7GaB0FAZPZfphBI/O05mBUGc/AWvoRaH3rjTDZI4B4+UN+fOCHtEHI="
  - secure: "jdPHUAjOnotn2U7pr2pVNrOLgsK21J350HFTDeBD3bQNDCbrZr1dVHe9PGnagO53Dxd+Wz1t2uMqJd5As6tWPYXQQ7Oj0z67rRNB57KUT5j6QNg8BnzRx8bWQFZGXaP908uIzJdvOa12HP30DVHwP6jPEiq+SW8bdI/ThwfPf4fMKQJW8xsNotEHzWelnc0P2DgwPYXD4/zfQ6mxPD537vlBrcKgRx1OojJQdnCR87zxVf+fUM3hovcStQiFtWlygjJevk82Fu+IE0CLb+cVlPAWtl6h+yzDiXroKUB4hGcCmEkO1WULDHQgx3a6bwkqDH4L74hgtqnmK/kWsnJsoISgHljBhyqLhikcwQgRFR3kfwc0VQA0vXTOHuahoJEfHUT1yOryfwuKN5z3855H/KHv1/5JxGmO5wxPzkSTP5nvJDYjmlKiwb9AOg5i7BAdwieMGSYHV9UfSsE7ZRQ8E534anuFi0sI7EWcD51fYZylyatAYu+bTtunSR3/dUJrO6jEhAWgUsfTCXRche7A9g62bc1YKKbgOlEG4sN7b0xfHRm2YV67owQMUkIrDB1UAPItw2Gyq8UhFyrQxq0IlrzrMuuFV+8mRX60Drav5ZPEJTYl00qQ3qFKuXNaR1iR50fR7wuVzcnzdD0nRjskbsTWDwJUbzbpeeWDJEUIFFM="
  - secure: "Ey+wglKvgfxhAFM7JQHWRxdep6wbmajV87vcIla7H38/08abjLQBN+O6NXESQQDAWGWSR7A6HGPmnEFD+PYqgiqFS2NJVKWm9Y1NFh+i2HVSow15fnjMTskLR629EgR/vTUUGxHq9AV7vlBlmojvZvO6zZaAPKTvO/XImIEGhkGGtPvFXPtFpRLeZcQ2xbF4fIc7Ce0Ywv7rEM9nPLvSTuDhJpvUik7SzpHVDrhdOgxQeIjp2PbFvweTmB5SywhE5GV46n5Teo8WSBriC0mvQ1n+FHsi/RCagn66Q9KU5pxbrD0CUH12sK4uUvwD4Nc+a44wfkM4j4enV7bKOWlujbt+GSUvyiwcPaBU3/OsGfJwWtgDgvjsLI4G9772sxxRuvB5HXmXmWkAXjDG+sfC2PuBQ3Mk7yQ73EDpv7reCpLb3uVONnysmm0ddbQrWUA8WGMV9MKzUO84Rj7Ri4p0Qm4xNUE2wG0TRMISLzxt1JhEGlSz2W9dFWMlqpaINv2P1N1LIImqrNROiMGjtgG5LkfhBeyCPbGWZx1xPIAO2d5GtFJwtc1vxkUOff1zDIqjpIwNYqAfYFKyYKtAhAcM6smYgAUkoP2rkMrWxl/sHs8ShuF9J8wh1ydLb4vVDB86KBROPoDGRJiUV9Zb/O9U4qmt0fbA1ZQIxMll+rirx7Y="
